import { getDefinition } from '../engine/exercises/definitions';
import { CONTENT_SCHEMA_VERSION, type ContentItem } from './library';

/**
 * Starter library content. ALL items are DRAFTS awaiting clinical review (approval on hold): none
 * is published, so none is shown to patients until a named reviewer approves that exact version.
 * No media is included — media needs licensed assets with recorded rights before it can be added.
 *
 * The four camera-guided items are the ones with a per-exercise camera definition in the engine;
 * their QA level is "synthetic tests only" until real-device QA is recorded (Phase 2 / Phase 20).
 */

const OWNER = 'Clinical lead — review pending (approval on hold)';
const base = { schema: CONTENT_SCHEMA_VERSION, version: '0.1.0', media: [], alternatives: [], source: { kind: 'authored' as const }, locale: 'en' as const, createdAt: '2026-09-27T00:00:00.000Z', review: { status: 'draft' as const, owner: OWNER } };
const cam = (definitionId: 'knee_flexion' | 'straight_leg_raise' | 'shoulder_flexion' | 'shoulder_abduction') => ({
  status: 'camera_guided' as const,
  definitionId,
  definitionVersion: getDefinition(definitionId).version,
  qa: 'synthetic_tested' as const,
  qaEvidence: 'Engine unit tests on synthetic landmark sequences (src/engine/exercises). No real-device QA recorded yet.',
});
const none = { status: 'not_camera_guided' as const };

export const SEED_CONTENT: ContentItem[] = [
  // ---- Camera-guided subset (per-exercise camera definitions exist) ----
  { ...base, id: 'standing-knee-bend', title: 'Standing knee bend', summary: 'Bend the knee to bring the heel toward the buttock, then lower slowly.', instructions: ['Stand side-on to the camera holding a chair or worktop.', 'Bend the knee, bringing the heel up behind you as far as is comfortable.', 'Hold for the time set, then lower slowly.'], goals: ['mobility'], regions: ['knee'], position: 'standing', equipment: ['chair'], difficulty: 1, accessibility: ['no_floor_work', 'limited_space'], precautions: ['Stop if pain increases sharply or you feel unsteady.'], defaultDosage: { sets: 2, reps: 10, holdSeconds: 2, frequencyPerWeek: 5 }, camera: cam('knee_flexion'), alternatives: [{ itemId: 'seated-knee-bend', reason: 'Seated option if standing balance is limited' }] },
  { ...base, id: 'straight-leg-raise', title: 'Straight leg raise', summary: 'Lying on your back, lift the straight leg and lower it slowly.', instructions: ['Lie on your back, the other knee bent with the foot flat.', 'Tighten the thigh of the straight leg and lift it to the height of the bent knee.', 'Lower slowly.'], goals: ['strength', 'control'], regions: ['knee', 'hip'], position: 'supine', equipment: ['none'], difficulty: 2, accessibility: ['no_equipment'], precautions: ['Stop if you feel pain in the lower back.'], defaultDosage: { sets: 2, reps: 10, holdSeconds: 2, frequencyPerWeek: 5 }, camera: cam('straight_leg_raise'), alternatives: [{ itemId: 'quad-set', reason: 'Easier start: tightening without lifting' }] },
  { ...base, id: 'arm-raise-forward', title: 'Arm raise forwards', summary: 'Raise the straight arm forwards and up, then lower slowly.', instructions: ['Stand side-on to the camera, arm by your side, thumb forwards.', 'Raise the arm forwards and up within the range your physiotherapist set.', 'Lower slowly.'], goals: ['mobility'], regions: ['shoulder'], position: 'standing', equipment: ['none'], difficulty: 1, accessibility: ['no_floor_work', 'no_equipment'], precautions: ['Keep within the range your physiotherapist set; stop if pain increases sharply.'], defaultDosage: { sets: 2, reps: 10, holdSeconds: 1, frequencyPerWeek: 5 }, camera: cam('shoulder_flexion'), alternatives: [{ itemId: 'pendulum', reason: 'Gentler option when raising the arm is painful' }] },
  { ...base, id: 'arm-raise-side', title: 'Arm raise to the side', summary: 'Raise the arm out to the side within the set range, then lower slowly.', instructions: ['Face the camera, arms by your sides.', 'Raise the arm out to the side within the range your physiotherapist set.', 'Lower slowly.'], goals: ['mobility'], regions: ['shoulder'], position: 'standing', equipment: ['none'], difficulty: 1, accessibility: ['no_floor_work', 'no_equipment'], precautions: ['Keep within the set range; stop if pain increases sharply.'], defaultDosage: { sets: 2, reps: 10, holdSeconds: 1, frequencyPerWeek: 5 }, camera: cam('shoulder_abduction') },
  // ---- Not camera-guided (instructions and dosage only; patient self-reports completion) ----
  { ...base, id: 'seated-knee-bend', title: 'Seated knee bend', summary: 'Sitting, slide the foot back under the chair to bend the knee.', instructions: ['Sit tall on a firm chair, feet flat.', 'Slide the foot back under the chair as far as is comfortable.', 'Hold, then slide it forward again.'], goals: ['mobility'], regions: ['knee'], position: 'seated', equipment: ['chair'], difficulty: 1, accessibility: ['seated_option', 'no_floor_work', 'limited_space'], precautions: ['Stop if pain increases sharply.'], defaultDosage: { sets: 2, reps: 10, holdSeconds: 3, frequencyPerWeek: 5 }, camera: none },
  { ...base, id: 'quad-set', title: 'Thigh tightening (quad set)', summary: 'Tighten the front of the thigh to press the back of the knee down.', instructions: ['Sit or lie with the leg straight.', 'Tighten the front of the thigh so the back of the knee presses down.', 'Hold, then relax.'], goals: ['strength', 'control'], regions: ['knee'], position: 'supine', equipment: ['towel'], difficulty: 1, accessibility: ['seated_option', 'limited_space'], precautions: ['None specific — stop if pain increases sharply.'], defaultDosage: { sets: 3, reps: 10, holdSeconds: 5, frequencyPerWeek: 7 }, camera: none },
  { ...base, id: 'sit-to-stand', title: 'Sit to stand', summary: 'Stand up from a chair and sit down again with control.', instructions: ['Sit near the front of a firm chair, feet hip-width apart.', 'Lean forward and stand up, using your hands if you need to.', 'Sit back down slowly.'], goals: ['strength', 'function'], regions: ['knee', 'hip'], position: 'seated', equipment: ['chair'], difficulty: 2, accessibility: ['no_floor_work', 'limited_space'], precautions: ['Have the chair against a wall so it cannot slide.', 'Stop if you feel dizzy.'], defaultDosage: { sets: 2, reps: 8, frequencyPerWeek: 5 }, camera: none },
  { ...base, id: 'heel-raise', title: 'Heel raises', summary: 'Rise up onto your toes, then lower slowly.', instructions: ['Stand holding a worktop, feet hip-width apart.', 'Rise up onto your toes.', 'Lower slowly.'], goals: ['strength', 'balance'], regions: ['ankle'], position: 'standing', equipment: ['wall'], difficulty: 2, accessibility: ['no_floor_work', 'limited_space'], precautions: ['Hold a support throughout.'], defaultDosage: { sets: 2, reps: 10, frequencyPerWeek: 5 }, camera: none, alternatives: [{ itemId: 'seated-heel-raise', reason: 'Seated option' }] },
  { ...base, id: 'seated-heel-raise', title: 'Seated heel raises', summary: 'Sitting, lift the heels and lower them.', instructions: ['Sit on a chair, feet flat.', 'Lift both heels, keeping the toes on the floor.', 'Lower slowly.'], goals: ['mobility', 'strength'], regions: ['ankle'], position: 'seated', equipment: ['chair'], difficulty: 1, accessibility: ['seated_option', 'no_floor_work', 'limited_space'], precautions: ['None specific.'], defaultDosage: { sets: 2, reps: 15, frequencyPerWeek: 5 }, camera: none },
  { ...base, id: 'bridge', title: 'Bridge', summary: 'Lying on your back, lift the hips and lower them.', instructions: ['Lie on your back, knees bent, feet flat.', 'Squeeze the buttocks and lift the hips off the floor.', 'Lower slowly.'], goals: ['strength', 'control'], regions: ['hip', 'lower_back'], position: 'supine', equipment: ['none'], difficulty: 2, accessibility: ['no_equipment'], precautions: ['Stop if it brings on back or leg pain.'], defaultDosage: { sets: 2, reps: 10, holdSeconds: 3, frequencyPerWeek: 4 }, camera: none },
  { ...base, id: 'clamshell', title: 'Clamshell', summary: 'Lying on your side, open and close the top knee.', instructions: ['Lie on your side, knees bent, feet together.', 'Keeping the feet together, lift the top knee.', 'Lower slowly without rolling backwards.'], goals: ['strength'], regions: ['hip'], position: 'side_lying', equipment: ['none'], difficulty: 1, accessibility: ['no_equipment'], precautions: ['If you have a hip replacement, follow your surgeon’s movement advice.'], defaultDosage: { sets: 2, reps: 12, frequencyPerWeek: 4 }, camera: none },
  { ...base, id: 'pendulum', title: 'Arm pendulum', summary: 'Let the arm hang and swing gently in small circles.', instructions: ['Lean forward, supporting yourself on a table with the other hand.', 'Let the arm hang relaxed.', 'Swing it gently in small circles by rocking your body.'], goals: ['mobility', 'pain_relief'], regions: ['shoulder'], position: 'standing', equipment: ['table'], difficulty: 1, accessibility: ['no_floor_work', 'one_arm'], precautions: ['Keep the movement small and relaxed.'], defaultDosage: { sets: 1, durationSeconds: 60, frequencyPerWeek: 7 }, camera: none },
  { ...base, id: 'chin-tuck', title: 'Chin tuck', summary: 'Glide the head straight back, keeping the eyes level.', instructions: ['Sit tall, looking straight ahead.', 'Glide your head straight back, making a double chin; do not tip it down.', 'Hold, then relax.'], goals: ['mobility', 'control'], regions: ['neck'], position: 'seated', equipment: ['chair'], difficulty: 1, accessibility: ['seated_option', 'no_floor_work', 'limited_space'], precautions: ['Stop straight away if you feel dizzy, see double or get arm tingling.'], defaultDosage: { sets: 2, reps: 8, holdSeconds: 3, frequencyPerWeek: 7 }, camera: none },
  { ...base, id: 'pelvic-tilt', title: 'Pelvic tilt', summary: 'Lying on your back, gently flatten and arch the lower back.', instructions: ['Lie on your back, knees bent.', 'Gently flatten your lower back into the floor.', 'Relax back to the start.'], goals: ['mobility', 'control'], regions: ['lower_back'], position: 'supine', equipment: ['none'], difficulty: 1, accessibility: ['no_equipment'], precautions: ['Stop if it brings on leg pain, pins and needles or numbness.'], defaultDosage: { sets: 2, reps: 10, frequencyPerWeek: 7 }, camera: none },
  { ...base, id: 'supported-single-leg-stand', title: 'Supported single-leg stand', summary: 'Stand on one leg holding a support.', instructions: ['Stand at a worktop with both hands on it.', 'Lift one foot slightly off the floor and hold.', 'Put the foot down whenever you need to.'], goals: ['balance'], regions: ['whole_body', 'ankle', 'hip'], position: 'standing', equipment: ['table'], difficulty: 2, accessibility: ['no_floor_work', 'limited_space'], precautions: ['Only with a sturdy support in front of you and clear floor around you.', 'If you have fallen in the last year, have someone next to you.'], defaultDosage: { sets: 3, holdSeconds: 10, frequencyPerWeek: 5 }, camera: none },
  { ...base, id: 'seated-march', title: 'Seated marching', summary: 'Sitting, lift the knees alternately.', instructions: ['Sit tall on a firm chair.', 'Lift one knee, lower it, then the other.', 'Keep a steady rhythm.'], goals: ['endurance', 'mobility'], regions: ['hip', 'whole_body'], position: 'seated', equipment: ['chair'], difficulty: 1, accessibility: ['seated_option', 'no_floor_work', 'limited_space'], precautions: ['None specific.'], defaultDosage: { sets: 2, durationSeconds: 60, frequencyPerWeek: 5 }, camera: none },
];
