// Generates docs/I18N_REVIEW.md: every UI string with its English text and the Tamil draft (or MISSING),
// for review by a qualified Tamil-speaking clinician/translator. Run: node scripts/i18n-review.mjs
import { readFileSync, writeFileSync } from 'node:fs';
const read = (f) => readFileSync(new URL(`../src/i18n/${f}`, import.meta.url), 'utf8');
const pairs = (s) => Object.fromEntries([...s.matchAll(/^\s+'([a-z0-9_.]+)':\s*(['"`])((?:\\.|(?!\2).)*)\2,?$/gm)].map((m) => [m[1], m[3].replace(/\\'/g, "'")]));
const en = pairs(read('en.ts'));
const ta = pairs(read('ta.ts'));
const keys = Object.keys(en);
const groups = {};
for (const k of keys) (groups[k.split('.')[0]] ??= []).push(k);
const esc = (s) => s.replace(/\|/g, '\\|');
let out = `# English / Tamil copy review sheet\n\nGenerated by \`scripts/i18n-review.mjs\` — do not edit by hand. ${Object.keys(ta).length} of ${keys.length} UI strings have a Tamil **draft**; none has been reviewed. Missing strings fall back to English.\n\n`;
out += '**Not in this sheet — clinical questionnaires.** The history and red-flag questionnaires (`src/clinical/intake.ts`, `safety.ts`, `regionQuestionnaires.ts`) are English-only, versioned clinical instruments. They must be translated by a qualified translator, back-translated, clinically reviewed and released as separate versioned questionnaires. They are not machine-translated.\n\n';
out += '| Area | Strings | Tamil drafts |\n|---|---|---|\n' + Object.entries(groups).map(([g, ks]) => `| ${g} | ${ks.length} | ${ks.filter((k) => ta[k]).length} |`).join('\n') + '\n\n';
for (const [g, ks] of Object.entries(groups)) {
  out += `## ${g}\n\n| Key | English | Tamil (draft) | Reviewer / date |\n|---|---|---|---|\n`;
  for (const k of ks) out += `| \`${k}\` | ${esc(en[k])} | ${ta[k] ? esc(ta[k]) : '**MISSING**'} |  |\n`;
  out += '\n';
}
writeFileSync(new URL('../docs/I18N_REVIEW.md', import.meta.url), out);
console.log(`docs/I18N_REVIEW.md: ${keys.length} keys, ${Object.keys(ta).length} Tamil drafts`);
