import { useMemo, useState } from 'react';
import { buildRuleDraft, validateDraft, type DraftFinding, type DraftSection } from '../../clinical/consultation';
import { buildEvidence } from '../../clinical/evidence';
import { lastDataChange } from '../../clinical/report';
import { Notice } from '../../components/ui';
import type { Assessment, DB, DraftDecision } from '../../data/models';
import { fmtDateTime } from '../../data/queries';
import { insert, uuid } from '../../data/store';

/**
 * Clinician review of the structured consultation draft (Phases 7–8). The draft is generated from
 * the current evidence every time it is opened; every statement shows the evidence it cites. The
 * clinician accepts, edits, rejects or defers each statement — the AI proposal is stored verbatim
 * next to the decision — and records examination findings. Nothing here reaches the patient or the
 * report as a conclusion: only the signed clinical impression does.
 */

const SECTION_TITLES: Record<DraftSection, string> = {
  summary: 'Intake summary (patient-reported)',
  observations: 'Observations (camera-estimated / algorithmic)',
  safetyFlags: 'Safety flags',
  contradictions: 'Contradictions to clarify',
  considerations: 'Considerations (versioned rule set)',
};

export function DraftReview({ db, a, actorId }: { db: DB; a: Assessment; actorId: string }) {
  const evidence = useMemo(() => buildEvidence(db, a.id), [db, a.id]);
  const draft = useMemo(() => buildRuleDraft(db, a.id), [db, a.id]);
  const check = useMemo(() => validateDraft(draft, evidence), [draft, evidence]);
  const byId = new Map(evidence.map((e) => [e.id, e]));
  const decisions = (db.draftDecisions ?? []).filter((d) => d.assessmentId === a.id);
  const exams = (db.examFindings ?? []).filter((f) => f.assessmentId === a.id).sort((x, y) => x.at.localeCompare(y.at));
  const impression = db.impressions.filter((i) => i.assessmentId === a.id).sort((x, y) => y.at.localeCompare(x.at))[0];
  const staleSignOff = !!impression && impression.at < lastDataChange(db, a.id);
  const [editing, setEditing] = useState<string | null>(null);
  const [text, setText] = useState('');
  const [area, setArea] = useState('');
  const [finding, setFinding] = useState('');
  const shown = check.draft ?? draft;
  const currentTexts = new Set((['summary', 'observations', 'safetyFlags', 'contradictions', 'considerations'] as DraftSection[]).flatMap((s) => shown.sections[s].map((f) => f.text)));
  const orphaned = decisions.filter((d) => !currentTexts.has(d.proposal));

  const decide = (section: string, f: DraftFinding, action: DraftDecision['action'], editedText?: string) =>
    insert(
      'draftDecisions',
      { id: uuid(), assessmentId: a.id, draftSchema: draft.schema, generator: `${draft.generator.id}@${draft.generator.version}`, section, proposal: f.text, evidence: f.evidence, action, editedText, by: actorId, at: new Date().toISOString(), isDemo: a.isDemo },
      actorId,
      `draft:${action}`,
    );

  return (
    <div className="stack loose">
      <Notice tone="warn">
        <strong>AI draft — awaiting clinician review.</strong> Generated by {draft.generator.id}@{draft.generator.version} ({draft.generator.kind === 'rules' ? 'deterministic rules, no language model' : draft.generator.model}), schema {draft.schema}. It organises the recorded evidence; it does not diagnose, and nothing here is shown to the patient.
      </Notice>
      <div className="row wrap" style={{ gap: '0.5rem' }}>
        <span className={`state-pill ${draft.uncertainty === 'low' ? 'supportive' : draft.uncertainty === 'moderate' ? 'insufficient_evidence' : 'conflicting'}`}>Information completeness: {draft.uncertainty === 'low' ? 'no gaps found' : `${draft.uncertainty} uncertainty`}</span>
        {draft.uncertaintyReasons.map((r) => (
          <span key={r} className="xs muted">
            · {r}
          </span>
        ))}
      </div>
      {!check.ok && <Notice tone="danger">The validator removed {check.errors.length} statement(s) from this draft: {check.errors.map((e) => `${e.section} — ${e.reason}`).join('; ')}</Notice>}
      {staleSignOff && <Notice tone="warn">New evidence was recorded after your signed impression ({fmtDateTime(impression!.at)}). Review the draft and re-sign in Evidence &amp; reasoning.</Notice>}

      {(['safetyFlags', 'contradictions', 'summary', 'observations', 'considerations'] as DraftSection[]).map((s) =>
        shown.sections[s].length ? (
          <section key={s} className="panel stack tight">
            <h2>{SECTION_TITLES[s]}</h2>
            {shown.sections[s].map((f, i) => {
              const key = `${s}:${i}`;
              const last = decisions.filter((d) => d.proposal === f.text).sort((x, y) => y.at.localeCompare(x.at))[0];
              return (
                <div key={key} className="stack tight" style={{ borderTop: i ? '1px solid var(--line)' : undefined, paddingTop: i ? '0.5rem' : undefined }}>
                  <div>{last?.action === 'edit' ? <>{last.editedText} <span className="xs muted">(edited; AI proposal: “{f.text}”)</span></> : f.text}</div>
                  <div className="row wrap" style={{ gap: '0.3rem' }}>
                    {f.evidence.map((id) => (
                      <span key={id} className="badge" title={byId.get(id)?.value}>
                        {byId.get(id)?.label ?? id}
                      </span>
                    ))}
                  </div>
                  {editing === key ? (
                    <div className="stack tight">
                      <textarea className="input" aria-label="Edited statement" value={text} onChange={(e) => setText(e.target.value)} />
                      <div className="row">
                        <button className="btn primary sm" disabled={!text.trim()} onClick={() => { decide(s, f, 'edit', text.trim()); setEditing(null); }}>Save edit</button>
                        <button className="btn secondary sm" onClick={() => setEditing(null)}>Cancel</button>
                      </div>
                    </div>
                  ) : (
                    <div className="row wrap" style={{ gap: '0.4rem' }}>
                      <button className="btn secondary sm" onClick={() => decide(s, f, 'accept')}>Accept</button>
                      <button className="btn secondary sm" onClick={() => { setEditing(key); setText(last?.editedText ?? f.text); }}>Edit</button>
                      <button className="btn secondary sm" onClick={() => decide(s, f, 'reject')}>Reject</button>
                      <button className="btn ghost sm" onClick={() => decide(s, f, 'defer')}>Defer</button>
                      {last && <span className="xs muted">Last: {last.action} · {fmtDateTime(last.at)}{decisions.filter((d) => d.proposal === f.text).length > 1 ? ` · ${decisions.filter((d) => d.proposal === f.text).length} decisions` : ''}</span>}
                    </div>
                  )}
                </div>
              );
            })}
          </section>
        ) : null,
      )}

      <section className="grid cols-2">
        {(['missingData', 'followUpQuestions', 'suggestedTests'] as const).map((s) => (
          <div key={s} className="panel stack tight">
            <h3>{s === 'missingData' ? 'Missing data' : s === 'followUpQuestions' ? 'Follow-up questions' : 'Suggested tests and examinations'}</h3>
            {shown.sections[s].length ? (
              <ul className="small">
                {shown.sections[s].map((x) => (
                  <li key={x}>{x}</li>
                ))}
              </ul>
            ) : (
              <p className="small muted">None.</p>
            )}
          </div>
        ))}
      </section>

      <section className="panel stack tight">
        <h2>Examination findings</h2>
        <p className="small muted">What you examined in person — including everything the camera cannot measure. These are clinician findings in the evidence map and the report.</p>
        {exams.map((f) => (
          <div key={f.id} className="small">
            <strong>{f.area}:</strong> {f.text} <span className="xs muted">· {fmtDateTime(f.at)}</span>
          </div>
        ))}
        <div className="row wrap" style={{ alignItems: 'flex-end' }}>
          <label className="field" style={{ minWidth: '10rem' }}>
            <span>Area / test</span>
            <input className="input" value={area} onChange={(e) => setArea(e.target.value)} placeholder="e.g. Passive range, palpation" />
          </label>
          <label className="field grow">
            <span>Finding</span>
            <input className="input" value={finding} onChange={(e) => setFinding(e.target.value)} />
          </label>
          <button
            className="btn primary sm"
            disabled={!area.trim() || !finding.trim()}
            onClick={() => {
              insert('examFindings', { id: uuid(), assessmentId: a.id, area: area.trim(), text: finding.trim(), by: actorId, at: new Date().toISOString(), isDemo: a.isDemo }, actorId, 'exam_finding');
              setArea('');
              setFinding('');
            }}
          >
            Add finding
          </button>
        </div>
      </section>

      {orphaned.length > 0 && (
        <section className="panel stack tight">
          <h3>Earlier decisions on statements no longer in the draft</h3>
          <p className="xs muted">The evidence changed since these decisions; they are kept for the audit history.</p>
          {orphaned.map((d) => (
            <div key={d.id} className="xs">
              {fmtDateTime(d.at)} · {d.action} · “{d.proposal}”{d.editedText ? ` → “${d.editedText}”` : ''}
            </div>
          ))}
        </section>
      )}
    </div>
  );
}
