import { useEffect, useState } from 'react';
import './brand.css';

const base = '/brand/dheepika-lab/';
const symptoms = [
  ['Pain', '#B43D43'], ['Stiffness', '#A76513'], ['Weakness', '#4B64A8'],
  ['Numbness', '#6D55A1'], ['Tingling', '#087F79'],
] as const;

function Mark({ light = false }: { light?: boolean }) {
  return <img src={`${base}symbol-${light ? 'light' : 'dark'}.svg`} alt="Dheepika Lab movement mark" />;
}

export function BrandPreview() {
  const [cameraState, setCameraState] = useState<'ready' | 'lost'>('ready');
  const [evidenceOpen, setEvidenceOpen] = useState(false);
  useEffect(() => {
    const previous = document.title;
    document.title = 'Dheepika Lab — provisional brand preview';
    return () => { document.title = previous; };
  }, []);
  return <main id="main" className="dl-preview">
    <div className="dl-banner"><span>PROVISIONAL IDENTITY · DESIGN REVIEW</span><a href="/">Return to PhysioVision</a></div>
    <header className="dl-hero">
      <nav className="dl-nav" aria-label="Brand preview navigation"><div className="dl-wordmark"><Mark light /><span>Dheepika Lab</span></div><div className="dl-navlinks"><a href="#experience">Experience</a><a href="#system">System</a><a href="#assets">Assets</a></div></nav>
      <div className="dl-hero-grid"><div><div className="dl-kicker">CLINICAL MOVEMENT INTELLIGENCE</div><h1>See movement.<br/><em>Guide recovery.</em></h1><p>A considered identity for the moment a symptom becomes an observation, an observation becomes understanding, and understanding becomes a recovery plan.</p><a className="dl-button" href="#experience">Explore the experience <span aria-hidden="true">↗</span></a></div><div className="dl-hero-art" aria-label="Movement mark shown at large scale"><img src={`${base}symbol-light.svg`} alt=""/><span>01 / SYMPTOM</span><span>02 / MOVEMENT</span><span>03 / UNDERSTANDING</span></div></div>
      <div className="dl-hero-foot"><span>A mark built from an open movement arc and three tracked joints</span><span>Designed for Dheepika · Concept v0.1</span></div>
    </header>
    <section className="dl-section" id="experience"><div className="dl-section-head"><span className="dl-index">01 / THE EXPERIENCE</span><h2>Three modes.<br/>One clear language.</h2><p>Every screen says what was observed, what remains uncertain, and what happens next.</p></div>
      <div className="dl-mode-grid">
        <article className="dl-mode dl-patient"><div className="dl-mode-label">PATIENT · INTAKE</div><div className="dl-phone"><div className="dl-phone-top"><Mark/><span>Step 2 of 5</span></div><div className="dl-progress"><i/></div><div className="dl-eyebrow">TELL US WHERE IT HURTS</div><h3>Let’s understand your knee.</h3><p>Tap the area that feels different. You can choose more than one symptom.</p><div className="dl-knee-map" role="img" aria-label="Illustrative knee location, front view"><span>FRONT VIEW</span><div className="dl-leg"><i/></div><div className="dl-map-point"><b>01</b> Front of right knee</div></div><div className="dl-chips">{symptoms.map(([label, color]) => <span key={label} style={{'--chip': color} as React.CSSProperties}><i/>{label}</span>)}</div><button className="dl-cta" type="button">Continue <span aria-hidden="true">→</span></button></div><p className="dl-mode-note">Warm guidance, labeled symptoms, and no premature diagnosis.</p></article>
        <article className="dl-mode dl-camera"><div className="dl-mode-label">CAMERA LAB · TRACKING</div><div className="dl-camera-screen"><div className="dl-camera-top"><div className="dl-wordmark"><Mark light/><span>Dheepika Lab</span></div><span>HEEL SLIDE · RIGHT</span></div><div className="dl-camera-viewport"><div className="dl-grid"/><svg viewBox="0 0 260 310" aria-hidden="true"><path d="M57 196L105 167L162 223L220 238" stroke="#31CDBB" strokeWidth="4" fill="none" strokeLinecap="round"/><circle cx="105" cy="167" r="9" fill="#31CDBB"/><circle cx="162" cy="223" r="9" fill="#31CDBB"/><circle cx="220" cy="238" r="9" fill="#31CDBB"/><path d="M135 194A40 40 0 0 1 180 211" stroke="#fff" strokeWidth="2" fill="none"/></svg><span className="dl-reticle">CAPTURE AREA</span><span className="dl-camera-demo">ILLUSTRATIVE OVERLAY · NOT A CAMERA MEASUREMENT</span></div><div className={`dl-valid ${cameraState === 'lost' ? 'dl-lost' : ''}`} role="status"><span className="dl-state-dot"/>{cameraState === 'ready' ? 'Landmarks in view' : 'Tracking lost · knee hidden'}</div><h3>{cameraState === 'ready' ? 'Keep your right leg in frame.' : 'Move back until your knee is visible.'}</h3><p>{cameraState === 'ready' ? 'Begin when the camera confirms a clear view.' : 'Measurement paused. No angle is recorded while tracking is lost.'}</p><button onClick={() => setCameraState(cameraState === 'ready' ? 'lost' : 'ready')} type="button">Preview {cameraState === 'ready' ? 'lost tracking' : 'valid tracking'}</button></div><p className="dl-mode-note">One instruction, visible validity, and no invented value during low confidence.</p></article>
        <article className="dl-mode dl-clinician"><div className="dl-mode-label">CLINICIAN · EVIDENCE</div><div className="dl-clinician-screen"><div className="dl-clinician-header"><div className="dl-wordmark"><Mark/><span>Dheepika Lab</span></div><span>ASSESSMENT REVIEW</span></div><div className="dl-record"><span>DEMO RECORD · DP-01</span><h3>Right knee movement review</h3><p>Capture review · 12 Sep 2026</p></div><div className="dl-metric-row"><div><small>HEEL SLIDE · FLEXION</small><strong>120.2<span>°</span></strong><small>3 / 3 valid repetitions</small></div><div><small>BASELINE → CURRENT</small><strong>+8.4<span>°</span></strong><small>Compared with matched setup</small></div></div><div className="dl-finding"><span className="dl-source">CAMERA · QUALITY GATED</span><h4>Limited flexion observed</h4><p>Supported by the valid heel-slide capture. Clinical meaning requires review with history and examination.</p><button type="button" onClick={() => setEvidenceOpen(!evidenceOpen)} aria-expanded={evidenceOpen}>Why? <span aria-hidden="true">{evidenceOpen ? '−' : '+'}</span></button>{evidenceOpen && <div className="dl-evidence"><b>Evidence trail</b><p>Capture session → 3 valid repetitions → tracked hip, knee and ankle → clinician review pending.</p></div>}</div><div className="dl-audit">AI PRELIMINARY · REQUIRES CLINICIAN REVIEW</div></div><p className="dl-mode-note">Measurements stay linked to quality, source, and clinician judgment.</p></article>
      </div>
    </section>
    <section className="dl-section dl-system" id="system"><div className="dl-section-head"><span className="dl-index">02 / VISUAL SYSTEM</span><h2>Precise when it counts.<br/>Calm everywhere else.</h2></div><div className="dl-system-grid"><div className="dl-palette"><h3>Core palette</h3>{[['Clinical green','#0B2427'],['Clear teal','#087F79'],['Soft mineral','#F6F8F5'],['Dark text','#142B2D'],['Secondary text','#52686A'],['Caution','#A76513'],['Escalation','#B43D43']].map(([name, hex]) => <div key={hex} className="dl-swatch"><i style={{background:hex}}/><span>{name}</span><code>{hex}</code></div>)}</div><div className="dl-type"><h3>Type & measurement</h3><div className="dl-type-hero">Movement,<br/>made visible.</div><p>DejaVu Sans · self-hosted candidate. Noto Sans Tamil remains the required Tamil face at rollout.</p><div className="dl-number">120.2<span>°</span></div><small>Tabular numerals keep values stable as they change.</small></div></div></section>
    <section className="dl-section dl-assets" id="assets"><div className="dl-section-head"><span className="dl-index">03 / APPLICATION</span><h2>One mark, every context.</h2><p>Vector assets are candidates. The current production favicon and public name remain PhysioVision until the name is confirmed.</p></div><div className="dl-asset-grid"><div><img src={`${base}horizontal-dark.svg`} alt="Horizontal dark Dheepika Lab wordmark"/><small>HORIZONTAL · LIGHT SURFACE</small></div><div className="dl-inverse"><img src={`${base}horizontal-light.svg`} alt="Horizontal light Dheepika Lab wordmark"/><small>HORIZONTAL · DARK SURFACE</small></div><div><img src={`${base}stacked-dark.svg`} alt="Stacked Dheepika Lab wordmark"/><small>STACKED · REPORT COVER</small></div><div className="dl-icon-sizes">{[16,24,48,128].map(size => <span key={size}><img width={size} height={size} src={`${base}symbol-dark.svg`} alt={`Symbol at ${size} pixels`}/><small>{size} px</small></span>)}</div></div><div className="dl-report"><div className="dl-report-top"><img src={`${base}horizontal-dark.svg`} alt="Dheepika Lab"/><span>CLINICAL MOVEMENT REPORT</span></div><div className="dl-report-rule"/><p>ASSESSMENT · 01 / 14</p><h3>Understanding<br/>movement.</h3><div className="dl-report-bottom"><span>DEMO RECORD · DP-01<br/>Illustrative cover, no patient data</span><span>AI PRELIMINARY<br/>Requires clinician review</span></div></div></section>
    <footer className="dl-footer"><span>Dheepika Lab · provisional identity concept</span><a href="/">Return to the working app ↗</a></footer>
  </main>;
}
